# Generated by Django 2.0.5 on 2018-06-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0002_auto_20180608_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='family',
        ),
        migrations.AddField(
            model_name='familymember',
            name='last_name',
            field=models.CharField(choices=[('Dube', 'Dube'), ('Mabuto', 'Mabuto'), ('Kubiku', 'Kubiku')], default=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='Family',
        ),
    ]
